@echo off
echo Cleaning up old documentation files...
echo.

REM Delete all the old markdown files (keep only essential ones)
if exist ACTION_CHECKLIST.md del /q ACTION_CHECKLIST.md
if exist AI_UNDERSTANDING_FIX.md del /q AI_UNDERSTANDING_FIX.md
if exist ALL_CHANGES_SUMMARY.md del /q ALL_CHANGES_SUMMARY.md
if exist ALL_ERRORS_FIXED.md del /q ALL_ERRORS_FIXED.md
if exist ALL_FIXES_COMPLETE.md del /q ALL_FIXES_COMPLETE.md
if exist ALL_LANGUAGES_FIXED.md del /q ALL_LANGUAGES_FIXED.md
if exist ALL_LANGUAGES_TEST_GUIDE.md del /q ALL_LANGUAGES_TEST_GUIDE.md
if exist AWS_ARCHITECTURE_SIMPLE.md del /q AWS_ARCHITECTURE_SIMPLE.md
if exist AWS_CONFIGURATION_COMPLETE.md del /q AWS_CONFIGURATION_COMPLETE.md
if exist AWS_QUICK_REFERENCE.md del /q AWS_QUICK_REFERENCE.md
if exist AWS_SERVICES_ACTUAL_STATUS.md del /q AWS_SERVICES_ACTUAL_STATUS.md
if exist AWS_SERVICES_INTEGRATION.md del /q AWS_SERVICES_INTEGRATION.md
if exist AWS_SERVICES_SETUP_GUIDE.md del /q AWS_SERVICES_SETUP_GUIDE.md
if exist BEDROCK_VALIDATION_FIX.md del /q BEDROCK_VALIDATION_FIX.md
if exist BEFORE_AFTER_COMPARISON.md del /q BEFORE_AFTER_COMPARISON.md
if exist BEFORE_AFTER_STEPS.md del /q BEFORE_AFTER_STEPS.md
if exist CHANGES_MADE_TODAY.md del /q CHANGES_MADE_TODAY.md
if exist CHANGES_SUMMARY.md del /q CHANGES_SUMMARY.md
if exist COMPLETE_SYSTEM_AUDIT.md del /q COMPLETE_SYSTEM_AUDIT.md
if exist CONNECTION_ERROR_FIX.md del /q CONNECTION_ERROR_FIX.md
if exist CONNECTION_ERROR_FIX_COMPLETE.md del /q CONNECTION_ERROR_FIX_COMPLETE.md
if exist DEPLOYMENT_READY.md del /q DEPLOYMENT_READY.md
if exist design.md del /q design.md
if exist DESIGN_IMPROVEMENTS.md del /q DESIGN_IMPROVEMENTS.md
if exist DOCUMENTATION.md del /q DOCUMENTATION.md
if exist DUPLICATE_MESSAGE_FIX.md del /q DUPLICATE_MESSAGE_FIX.md
if exist EMPTY_RESPONSE_FIX.md del /q EMPTY_RESPONSE_FIX.md
if exist ENHANCED_FEATURES.md del /q ENHANCED_FEATURES.md
if exist ERROR_CAUSE_AND_FIX.md del /q ERROR_CAUSE_AND_FIX.md
if exist FINAL_AWS_AUDIT_COMPLETE.md del /q FINAL_AWS_AUDIT_COMPLETE.md
if exist FINAL_CHECKLIST.md del /q FINAL_CHECKLIST.md
if exist FINAL_COMPLETE_FIX.md del /q FINAL_COMPLETE_FIX.md
if exist FINAL_FIXES_SUMMARY.md del /q FINAL_FIXES_SUMMARY.md
if exist FINAL_FIX_SCHEMES_DISPLAY.md del /q FINAL_FIX_SCHEMES_DISPLAY.md
if exist FINAL_FIX_SUMMARY.md del /q FINAL_FIX_SUMMARY.md
if exist FINAL_STEPS_FIX_SUMMARY.md del /q FINAL_STEPS_FIX_SUMMARY.md
if exist FINAL_THREE_FIXES.md del /q FINAL_THREE_FIXES.md
if exist FINAL_VERIFICATION_CHECKLIST.md del /q FINAL_VERIFICATION_CHECKLIST.md
if exist FINAL_VERIFICATION_COMPLETE.md del /q FINAL_VERIFICATION_COMPLETE.md
if exist FIXES_AND_AWS_INTEGRATION.md del /q FIXES_AND_AWS_INTEGRATION.md
if exist FIX_CHECKLIST.md del /q FIX_CHECKLIST.md
if exist FRONTEND_DISPLAY_FIX.md del /q FRONTEND_DISPLAY_FIX.md
if exist FRONTEND_NOT_SHOWING_RESPONSES.md del /q FRONTEND_NOT_SHOWING_RESPONSES.md
if exist HINDI_VOICE_FIX.md del /q HINDI_VOICE_FIX.md
if exist HOW_TO_CONFIGURE_AWS.md del /q HOW_TO_CONFIGURE_AWS.md
if exist INSTRUCTIONS_CONTEXT_FIX.md del /q INSTRUCTIONS_CONTEXT_FIX.md
if exist INTEGRATION_GUIDE.md del /q INTEGRATION_GUIDE.md
if exist JSON_DISPLAY_FIX.md del /q JSON_DISPLAY_FIX.md
if exist LANGUAGE_AND_SPEED_FIXES.md del /q LANGUAGE_AND_SPEED_FIXES.md
if exist LANGUAGE_MIXING_FIX.md del /q LANGUAGE_MIXING_FIX.md
if exist MASTER_CHECKLIST.md del /q MASTER_CHECKLIST.md
if exist PROJECT_STRUCTURE.md del /q PROJECT_STRUCTURE.md
if exist QUICK_FIX_REFERENCE.md del /q QUICK_FIX_REFERENCE.md
if exist QUICK_FIX_SUMMARY.md del /q QUICK_FIX_SUMMARY.md
if exist QUICK_PROMPTS_ENHANCED.md del /q QUICK_PROMPTS_ENHANCED.md
if exist QUICK_REFERENCE.md del /q QUICK_REFERENCE.md
if exist QUICK_START_ENHANCED.md del /q QUICK_START_ENHANCED.md
if exist QUICK_START_FINAL.md del /q QUICK_START_FINAL.md
if exist README_FIX_NOW.md del /q README_FIX_NOW.md
if exist README_SECURITY.md del /q README_SECURITY.md
if exist requirements.md del /q requirements.md
if exist SCHEME_SPECIFIC_STEPS_FIX.md del /q SCHEME_SPECIFIC_STEPS_FIX.md
if exist SECURITY_CHECKLIST.md del /q SECURITY_CHECKLIST.md
if exist SECURITY_SETUP_GUIDE.md del /q SECURITY_SETUP_GUIDE.md
if exist SMS_INTEGRATION_COMPLETE.md del /q SMS_INTEGRATION_COMPLETE.md
if exist SPEAKER_ICON_FIX.md del /q SPEAKER_ICON_FIX.md
if exist START_HERE.md del /q START_HERE.md
if exist START_HERE_FIX.md del /q START_HERE_FIX.md
if exist STEPS_DISPLAY_FINAL_FIX.md del /q STEPS_DISPLAY_FINAL_FIX.md
if exist STEPS_FIX_APPLIED.md del /q STEPS_FIX_APPLIED.md
if exist SUMMARY.md del /q SUMMARY.md
if exist TELUGU_LANGUAGE_MIX_FIX.md del /q TELUGU_LANGUAGE_MIX_FIX.md
if exist TEST_BEFORE_DEPLOYMENT.md del /q TEST_BEFORE_DEPLOYMENT.md
if exist TEST_SCHEME_DISPLAY.md del /q TEST_SCHEME_DISPLAY.md
if exist TEST_STEPS_DISPLAY.md del /q TEST_STEPS_DISPLAY.md
if exist TIMEOUT_FIX_EXPLANATION.md del /q TIMEOUT_FIX_EXPLANATION.md
if exist TROUBLESHOOTING_STEPS.md del /q TROUBLESHOOTING_STEPS.md
if exist TTS_FIX_TAMIL_LANGUAGES.md del /q TTS_FIX_TAMIL_LANGUAGES.md
if exist URGENT_FIX_APPLIED.md del /q URGENT_FIX_APPLIED.md
if exist URGENT_FIX_NO_RESPONSES.md del /q URGENT_FIX_NO_RESPONSES.md
if exist VOICE_AND_UI_FIXES.md del /q VOICE_AND_UI_FIXES.md
if exist VOICE_DEBUG_GUIDE.md del /q VOICE_DEBUG_GUIDE.md
if exist VOICE_FIX_SUMMARY.md del /q VOICE_FIX_SUMMARY.md
if exist VOICE_LANGUAGE_SUPPORT.md del /q VOICE_LANGUAGE_SUPPORT.md
if exist VOICE_RECORDING_TROUBLESHOOTING.md del /q VOICE_RECORDING_TROUBLESHOOTING.md
if exist VOICE_TROUBLESHOOTING.md del /q VOICE_TROUBLESHOOTING.md
if exist WHAT_CHANGED.md del /q WHAT_CHANGED.md
if exist WHAT_IS_HAPPENING.md del /q WHAT_IS_HAPPENING.md

echo.
echo ✅ Cleanup complete!
echo.
echo Files kept:
echo - README.md (main project documentation)
echo - DEPLOYMENT_GUIDE.md (deployment instructions)
echo - CONTRIBUTING.md (contribution guidelines)
echo - HACKATHON_DOCUMENTATION.md (NEW - consolidated documentation)
echo.
pause
